FROM node:16-alpine

WORKDIR /app

COPY ./package.json ./

RUN npm install

COPY . .

CMD ["npm", "run", "start"]

# dev 파일 추가 작성
# 운영환경은 빌드파일로 빠르게 사용자에게 제공하는 목적이 있고
# 개발환경은 잦은 수정과 빌드의 필요성이 있어서
# 개발환경인 Dockerfile.dev에서는 start를 하고
# 운영환경인 Dockerfile에서는 build를 함
# 빌드를 하면 이미 정적인 빌드 파일이 생긴 것이기 때문에 volumes으로 코드 수정을 적용하는 게 불가능함