FROM node:16-alpine AS build
# 이미지를 node:10으로 당겨왔다가 1시간동안 뻘짓함
# 도커 이미지 빌드 중 npm run build에서 막히길래 한참 찾았음

WORKDIR /app

COPY ./package.json ./

RUN npm install
# package.json을 해야 코드의 일부를 수정할 때 매번 종속성까지 다시 다운받지 않을 수 있음

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]