version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend/:/app
    stdin_open: true
    environment:
      - WDS_SOCKET_PORT=${WS_PORT}

  nginx:
    restart: no
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
      
  mysql:
    build:
      dockerfile: Dockerfile.dev
      context: ./mysql
    restart: no
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - ./backend/:/app
    ports:
      - "8080:8080"
      # react는 이미지로 컨테이너 생성시 포트지정을 안해줘도 nginx가 3000을 listen하고 있어서 실행이 가능한데 go는 그렇지 않아서 포트 지정을 해줘야함