FROM golang:1.18.1-buster

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

RUN go install -mod=mod github.com/githubnemo/CompileDaemon
# go get github~ 로는 설치가 안됨
# 특히 저 -mod=mod가 뭔지 찾아봐야할 듯

COPY . .
# CMD ["go", "run", "main.go" ]
# build 뿐만 아니라 run도 코드 수정을 반영할 수 없음
# 그래서 compileDaemon 오픈 소스 활용

ENTRYPOINT CompileDaemon -polling -log-prefix=false -build="go build ./src/main.go" -command="./main" -directory="./"
# build로 build 명령어 작성하고
# command로 빌드한 빌드파일을 실행할 명령어 작성
