FROM golang:1.18.1-buster

WORKDIR /app

COPY go.mod go.sum ./
# go.mod를 따로 먼저 카피해서 종속성을 설치해줘야 함
# 안그러면 나중에 종속성과 관련 없는 부분이 수정되어도 빌드하면 종속성까지 다 다시 다운 받게 됨
# go.sum도 여기 넣어줘야함 이거 안넣어주면 컨테이너 빌드할 때 오류남

RUN go mod download
# go mod tidy 같은 느낌

COPY . .
# go mod, go.sum 제외한 파일 모두 복사

WORKDIR /app/src

EXPOSE 8080

CMD ["go", "run", "*.go" ]